CREATE TABLE patients(
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    date_of_birth DATE NOT NULL
);
CREATE TABLE invoices(
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    total_amount DECIMAL(8, 2) NOT NULL,
    generated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    payed_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    medical_history__id INT REFERENCES medical_histories(id)
);
CREATE TABLE medical_histories(
   id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    admitted_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    patient_id INT REFERENCES patients(id),
    status VARCHAR(255) NOT NULL
);
CREATE TABLE treatments(
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    type VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL
);
CREATE TABLE invoice_items(
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    unit_price DECIMAL(8, 2) NOT NULL,
    quantity INT NOT NULL,
    total_price DECIMAL(8, 2) NOT NULL,
    invoice_id INT REFERENCES invoices(id),
    treatment_id INT REFERENCES treatments(id)
);
CREATE TABLE treatment_history(
  treatment_id INT REFERENCES treatments(id),
  medical_history_id INT REFERENCES medical_histories(id) 
);

CREATE INDEX medical_history__id_idx ON invoices(medical_history__id);
CREATE INDEX patient_id_idx ON medical_histories(patient_id);
CREATE INDEX invoice_id_idx ON invoice_items(invoice_id);
CREATE INDEX treatment_id_idx ON invoice_items(treatment_id);
CREATE INDEX treatment_id_idx ON treatment_history(treatment_id);
CREATE INDEX medical_history_id_idx ON treatment_history(medical_history_id);